# Generated by Django 4.2.5 on 2023-11-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='uzs_price',
        ),
        migrations.AddField(
            model_name='product',
            name='usd_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Цена в долларах'),
        ),
    ]
