# Generated by Django 4.2.5 on 2023-11-14 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0005_alter_subcategory_cornice_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='category_common_price_usd',
            field=models.SmallIntegerField(default=0, verbose_name='Цена от'),
        ),
    ]
