# Generated by Django 4.2.5 on 2023-11-14 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0007_subcategory_category_common_price_uzs_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Kind',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='kind',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='category',
            new_name='kind',
        ),
    ]
