# Generated by Django 4.2.5 on 2023-11-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0009_rename_subcategory_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uzs_price',
            field=models.IntegerField(default=0, help_text='Данное поле заполнять не нужно, цена будет рассчитываться от базовой цены в долларах', verbose_name='Базовая цена в сумах'),
        ),
        migrations.AlterField(
            model_name='product',
            name='usd_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Базовая цена в долларах'),
        ),
    ]
