# Generated by Django 4.2.5 on 2023-11-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0011_product_usd_electrical_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='usd_cornice_type_price',
            field=models.PositiveIntegerField(default=0, verbose_name="Цена в долларах типа карниза 'Алюминевый'"),
        ),
        migrations.AddField(
            model_name='product',
            name='uzs_cornice_type_price',
            field=models.PositiveIntegerField(default=0, help_text="Данное поле заполнять не нужно, цена будет рассчитываться от цены карниза 'Алюминевый' в долларах", verbose_name="Цена в суммах типа карниза 'Алюминевый'"),
        ),
        migrations.AlterField(
            model_name='product',
            name='usd_electrical_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена с электроприводом в долларах'),
        ),
        migrations.AlterField(
            model_name='product',
            name='usd_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Базовая цена в долларах'),
        ),
        migrations.AlterField(
            model_name='product',
            name='uzs_electrical_price',
            field=models.PositiveIntegerField(default=0, help_text='Данное поле заполнять не нужно, цена будет рассчитываться от цены элекртопривода в долларах', verbose_name='Цена с электроприводом в суммах'),
        ),
        migrations.AlterField(
            model_name='product',
            name='uzs_price',
            field=models.PositiveIntegerField(default=0, help_text='Данное поле заполнять не нужно, цена будет рассчитываться от базовой цены в долларах', verbose_name='Базовая цена в сумах'),
        ),
    ]
