# Generated by Django 4.2.5 on 2023-12-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0013_product_is_bestseller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='control',
            field=models.CharField(choices=[('left', 'Слева'), ('center', 'По середине'), ('right', 'Справа')], default='left', max_length=50, verbose_name='Управление'),
        ),
    ]
