# Generated by Django 4.2.5 on 2024-02-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0015_product_has_center_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_rounding',
            field=models.BooleanField(default=False, verbose_name='Есть ли округление до пол квадрата'),
        ),
    ]
