# Generated by Django 4.2.5 on 2024-02-24 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0016_product_has_rounding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='usd_cornice_type_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='uzs_cornice_type_price',
        ),
    ]
