# Generated by Django 4.2.5 on 2023-09-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                max_length=15, null=True, verbose_name="Номер телефона"
            ),
        ),
    ]
