# Generated by Django 4.2.5 on 2023-10-23 20:17

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название категории"
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Название категории",
                    ),
                ),
                (
                    "name_uz",
                    models.CharField(
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Название категории",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        default="",
                        help_text="Данное поле заполнять не нужно.",
                        verbose_name="Ссылка категории",
                    ),
                ),
                (
                    "show_on_homepage",
                    models.BooleanField(
                        default=False,
                        help_text="При выборе данного пункта, все продукты этой категории будут показаны на главной странице",
                        verbose_name="Показать на главной",
                    ),
                ),
                (
                    "make_bestseller",
                    models.BooleanField(
                        default=False,
                        help_text="При выборе данного пункта, покажет все товары данной категории в секции 'Хиты продаж' ",
                        verbose_name="Сделать бестселлером",
                    ),
                ),
                (
                    "width_rounding",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Округление по ширине для всех товаров категории",
                    ),
                ),
                (
                    "width_rounding_ru",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Округление по ширине для всех товаров категории",
                    ),
                ),
                (
                    "width_rounding_uz",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Округление по ширине для всех товаров категории",
                    ),
                ),
                (
                    "length_rounding",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Округление по длине для всех товаров категории",
                    ),
                ),
                (
                    "length_rounding_ru",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Округление по длине для всех товаров категории",
                    ),
                ),
                (
                    "length_rounding_uz",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Округление по длине для всех товаров категории",
                    ),
                ),
                (
                    "product_width_from",
                    models.IntegerField(default=0, null=True, verbose_name="Ширина от"),
                ),
                (
                    "product_width_to",
                    models.IntegerField(default=0, null=True, verbose_name="Ширина до"),
                ),
                (
                    "product_length_from",
                    models.IntegerField(default=0, null=True, verbose_name="Длина от"),
                ),
                (
                    "product_length_to",
                    models.IntegerField(default=0, null=True, verbose_name="Длина до"),
                ),
                (
                    "category_usd_price",
                    models.IntegerField(default=0, verbose_name="Стоимость в долларах"),
                ),
                (
                    "discount",
                    models.SmallIntegerField(default=0, verbose_name="Процент скидки"),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название клиента"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="clients/", verbose_name="Фото компании"
                    ),
                ),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(verbose_name="Текст комментария")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
            },
        ),
        migrations.CreateModel(
            name="FabricType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Тип ткани")),
            ],
            options={
                "verbose_name": "Тип ткани",
                "verbose_name_plural": "Типы ткани",
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(verbose_name="Текст отзыва")),
                ("body_ru", models.TextField(null=True, verbose_name="Текст отзыва")),
                ("body_uz", models.TextField(null=True, verbose_name="Текст отзыва")),
                (
                    "author",
                    models.CharField(max_length=255, verbose_name="Автор отзыва"),
                ),
                (
                    "author_ru",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Автор отзыва"
                    ),
                ),
                (
                    "author_uz",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Автор отзыва"
                    ),
                ),
                (
                    "author_avatar",
                    models.ImageField(
                        upload_to="feedbacks/avatars/", verbose_name="Фото автора"
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=255, verbose_name="Компания автора"),
                ),
                (
                    "company_name_ru",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Компания автора"
                    ),
                ),
                (
                    "company_name_uz",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Компания автора"
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
            },
        ),
        migrations.CreateModel(
            name="HeroGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Заголовок слайдера"),
                ),
                (
                    "title_ru",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Заголовок слайдера"
                    ),
                ),
                (
                    "title_uz",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Заголовок слайдера"
                    ),
                ),
                ("body", models.TextField(verbose_name="Описание слайдера")),
                (
                    "body_ru",
                    models.TextField(null=True, verbose_name="Описание слайдера"),
                ),
                (
                    "body_uz",
                    models.TextField(null=True, verbose_name="Описание слайдера"),
                ),
                (
                    "img",
                    models.ImageField(
                        default="", upload_to="slides/", verbose_name="Фото слайда"
                    ),
                ),
            ],
            options={
                "verbose_name": "Слайд",
                "verbose_name_plural": "Слайды",
            },
        ),
        migrations.CreateModel(
            name="ImagesOnAboutPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="pages/about/", verbose_name="Фото"),
                ),
            ],
            options={
                "verbose_name": "Фотка на странице 'О компании'",
                "verbose_name_plural": "Фотки на странице 'О компании'",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="",
                        max_length=255,
                        unique=True,
                        verbose_name="Название продукта",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        default="",
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Название продукта",
                    ),
                ),
                (
                    "name_uz",
                    models.CharField(
                        default="",
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Название продукта",
                    ),
                ),
                (
                    "uzs_price",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        help_text="Данное поле заполнять не нужно.",
                        null=True,
                        verbose_name=" Цена в узбекских сумах",
                    ),
                ),
                (
                    "body",
                    models.TextField(default="", verbose_name="Описание продукта"),
                ),
                (
                    "body_ru",
                    models.TextField(
                        default="", null=True, verbose_name="Описание продукта"
                    ),
                ),
                (
                    "body_uz",
                    models.TextField(
                        default="", null=True, verbose_name="Описание продукта"
                    ),
                ),
                (
                    "placeholder",
                    models.ImageField(
                        null=True,
                        upload_to="products/placeholders/",
                        verbose_name="Заставка",
                    ),
                ),
                (
                    "manufacturer_country",
                    models.CharField(
                        default="", max_length=255, verbose_name="Страна производитель"
                    ),
                ),
                (
                    "manufacturer_country_ru",
                    models.CharField(
                        default="",
                        max_length=255,
                        null=True,
                        verbose_name="Страна производитель",
                    ),
                ),
                (
                    "manufacturer_country_uz",
                    models.CharField(
                        default="",
                        max_length=255,
                        null=True,
                        verbose_name="Страна производитель",
                    ),
                ),
                (
                    "control",
                    models.CharField(
                        choices=[("left", "Слева"), ("right", "Справа")],
                        default="left",
                        max_length=50,
                        verbose_name="Управление",
                    ),
                ),
                (
                    "cornice_type",
                    models.CharField(
                        choices=[
                            ("aluminum", "Алюминиевый"),
                            ("plastic", "Пластиковый"),
                        ],
                        default="aluminum",
                        max_length=50,
                        verbose_name="Тип карниза",
                    ),
                ),
                (
                    "control_type",
                    models.CharField(
                        choices=[
                            ("manual", "Ручной"),
                            ("electrically_driven", "С электроприводом"),
                        ],
                        default="manual",
                        max_length=50,
                        verbose_name="Тип управления",
                    ),
                ),
                (
                    "quantity",
                    models.SmallIntegerField(
                        default=0, verbose_name="Количество продукта"
                    ),
                ),
                (
                    "discount",
                    models.SmallIntegerField(
                        blank=True, default=0, null=True, verbose_name="Размер скидки"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата создания"),
                ),
                (
                    "slug",
                    models.SlugField(
                        default="",
                        help_text="Данное поле заполнять не нужно",
                        verbose_name="Ссылка продукта",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="web_site.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.CreateModel(
            name="ProductColorItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Цвет продукта"
                    ),
                ),
                (
                    "color_ru",
                    models.CharField(
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Цвет продукта",
                    ),
                ),
                (
                    "color_uz",
                    models.CharField(
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Цвет продукта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Цвет",
                "verbose_name_plural": "Цвета",
            },
        ),
        migrations.CreateModel(
            name="ProductDimming",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dimming", models.IntegerField(default=0, verbose_name="Затемнение")),
            ],
            options={
                "verbose_name": "Затеменение",
                "verbose_name_plural": "Затемнения",
            },
        ),
        migrations.CreateModel(
            name="ProductProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Свойство")),
            ],
            options={
                "verbose_name": "Свойство",
                "verbose_name_plural": "Свойства",
            },
        ),
        migrations.CreateModel(
            name="ProjectsGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название проекта"
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Название проекта",
                    ),
                ),
                (
                    "title_uz",
                    models.CharField(
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Название проекта",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        help_text="Показывается на главной странице",
                        max_length=255,
                        verbose_name="Подзаголовок проекта",
                    ),
                ),
                (
                    "subtitle_ru",
                    models.CharField(
                        help_text="Показывается на главной странице",
                        max_length=255,
                        null=True,
                        verbose_name="Подзаголовок проекта",
                    ),
                ),
                (
                    "subtitle_uz",
                    models.CharField(
                        help_text="Показывается на главной странице",
                        max_length=255,
                        null=True,
                        verbose_name="Подзаголовок проекта",
                    ),
                ),
                (
                    "short_description",
                    models.TextField(
                        help_text="Краткое описание для проекта, показывается на странице проектов",
                        null=True,
                        verbose_name="Краткое описание проекта",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="projects_gallery/", verbose_name="Фотография"
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        null=True, verbose_name="Описание проекта"
                    ),
                ),
                ("slug", models.SlugField(null=True, verbose_name="Слаг")),
            ],
            options={
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название вопроса"
                    ),
                ),
                ("video_link", models.URLField(verbose_name="Ссылка на видео")),
            ],
            options={
                "verbose_name": "Вопрос",
                "verbose_name_plural": "Вопросы",
            },
        ),
        migrations.CreateModel(
            name="SocialItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.CharField(max_length=500, verbose_name="Ссылка на соц сеть"),
                ),
                (
                    "icon",
                    models.ImageField(
                        help_text="Фото должно быть расширения PNG",
                        upload_to="socials/icons/",
                        verbose_name="Фото соц сети.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Социальная сеть",
                "verbose_name_plural": "Социальные сети",
            },
        ),
        migrations.CreateModel(
            name="Subcategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Название подкатегории"
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Название подкатегории"
                    ),
                ),
                (
                    "name_uz",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Название подкатегории"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        default="",
                        help_text="Данное поле заполнять не нужно",
                        verbose_name="Ссылка подкатегории",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        null=True,
                        upload_to="subcategories/",
                        verbose_name="Фото подкатегории",
                    ),
                ),
                (
                    "has_discount",
                    models.BooleanField(
                        default=False,
                        help_text="Есть ли скидка для всех товаров этой подкатегории",
                        verbose_name="Есть ли скида?",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="web_site.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подкатегория",
                "verbose_name_plural": "Подкатегории",
            },
        ),
        migrations.CreateModel(
            name="ProjectsGalleryImageItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to="projects_gallery/addons/",
                        verbose_name="Дополнительное фото",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="web_site.projectsgallery",
                        verbose_name="Проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Дополнительное фото",
                "verbose_name_plural": "Дополнительные фото",
            },
        ),
        migrations.CreateModel(
            name="ProductOptionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100, verbose_name="Название характеристики"
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        max_length=100,
                        null=True,
                        verbose_name="Название характеристики",
                    ),
                ),
                (
                    "title_uz",
                    models.CharField(
                        max_length=100,
                        null=True,
                        verbose_name="Название характеристики",
                    ),
                ),
                ("descr", models.TextField(verbose_name="Описание характеристики")),
                (
                    "descr_ru",
                    models.TextField(null=True, verbose_name="Описание характеристики"),
                ),
                (
                    "descr_uz",
                    models.TextField(null=True, verbose_name="Описание характеристики"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="web_site.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Характеристика",
                "verbose_name_plural": "Характеристики",
            },
        ),
        migrations.CreateModel(
            name="ProductImageItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="products/", verbose_name="Фото продукта"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="web_site.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото продукта",
                "verbose_name_plural": "Фотки продуктов",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="web_site.productcoloritem",
                verbose_name="Цвет продукта",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="dimming",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="products",
                to="web_site.productdimming",
                verbose_name="Затемнение",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="fabric_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="products",
                to="web_site.fabrictype",
                verbose_name="Тип ткани",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="fabric_type_ru",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="products",
                to="web_site.fabrictype",
                verbose_name="Тип ткани",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="fabric_type_uz",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="products",
                to="web_site.fabrictype",
                verbose_name="Тип ткани",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="property",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="products",
                to="web_site.productproperty",
                verbose_name="Свойство",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="property_ru",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="products",
                to="web_site.productproperty",
                verbose_name="Свойство",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="property_uz",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="products",
                to="web_site.productproperty",
                verbose_name="Свойство",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="subcategory",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="web_site.subcategory",
                verbose_name="Подкатегория",
            ),
        ),
        migrations.CreateModel(
            name="CommentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "img",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="comments/",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web_site.comment",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="comment",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="web_site.product",
            ),
        ),
    ]
