# Generated by Django 4.2.5 on 2023-09-19 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web_site", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Продукт", "verbose_name_plural": "Продукты"},
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                default="",
                help_text="Данное поле заполнять не нужно.",
                verbose_name="Ссылка категории",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="body",
            field=models.TextField(default="", verbose_name="Описание продукта"),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="web_site.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="control",
            field=models.CharField(
                choices=[("left", "Слева"), ("right", "Справа")],
                default="left",
                max_length=50,
                verbose_name="Управление",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="control_type",
            field=models.CharField(
                choices=[
                    ("manual", "Ручной"),
                    ("electrically_driven", "С электроприводом"),
                ],
                default="manual",
                max_length=50,
                verbose_name="Тип управления",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="cornice_type",
            field=models.CharField(
                choices=[("aluminum", "Алюминиевый"), ("plastic", "Пластиковый")],
                default="aluminum",
                max_length=50,
                verbose_name="Тип карниза",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="dimming",
            field=models.SmallIntegerField(default=0, verbose_name="Затемнение"),
        ),
        migrations.AddField(
            model_name="product",
            name="fabric_type",
            field=models.CharField(
                default="", max_length=255, verbose_name="Тип ткани"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="manufacturer_country",
            field=models.CharField(
                default="", max_length=255, verbose_name="Страна производитель"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="name",
            field=models.CharField(
                default="",
                max_length=255,
                unique=True,
                verbose_name="Название продукта",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="property",
            field=models.CharField(default="", max_length=255, verbose_name="Свойство"),
        ),
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.SmallIntegerField(
                default=0, verbose_name="Количество продукта"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                default="",
                help_text="Данное поле заполнять не нужно",
                verbose_name="Ссылка продукта",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="subcategory",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="web_site.subcategory",
                verbose_name="Подкатегория",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="usd_price",
            field=models.SmallIntegerField(default=0, verbose_name="Цена в y.e"),
        ),
        migrations.AddField(
            model_name="product",
            name="uzs_price",
            field=models.IntegerField(
                default=0,
                help_text="Данное поле заполнять не нужно, при добавлении цены в y.e данное поле будет заполнено автоматически",
                verbose_name=" Цена в узбекских сумах",
            ),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="slug",
            field=models.SlugField(
                default="",
                help_text="Данное поле заполнять не нужно",
                verbose_name="Ссылка подкатегории",
            ),
        ),
        migrations.CreateModel(
            name="ProductWidthItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "width",
                    models.CharField(
                        default="", max_length=100, unique=True, verbose_name="Ширина"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web_site.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ширина продукта",
            },
        ),
        migrations.CreateModel(
            name="ProductOptionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Название характеристики",
                    ),
                ),
                ("descr", models.TextField(verbose_name="Описание характеристики")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web_site.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductLengthItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "length",
                    models.CharField(
                        default="", max_length=100, unique=True, verbose_name="Длина"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web_site.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Длина продукта",
            },
        ),
        migrations.CreateModel(
            name="ProductImageItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="products/", verbose_name="Фото продукта"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web_site.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото продукта",
            },
        ),
        migrations.CreateModel(
            name="ProductColorItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Цвет продукта"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web_site.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Цвет",
            },
        ),
    ]
