# Generated by Django 4.2.5 on 2023-10-23 20:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_site", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectsgallery",
            name="description_ru",
            field=ckeditor.fields.RichTextField(
                null=True, verbose_name="Описание проекта"
            ),
        ),
        migrations.AddField(
            model_name="projectsgallery",
            name="description_uz",
            field=ckeditor.fields.RichTextField(
                null=True, verbose_name="Описание проекта"
            ),
        ),
        migrations.AddField(
            model_name="projectsgallery",
            name="short_description_ru",
            field=models.TextField(
                help_text="Краткое описание для проекта, показывается на странице проектов",
                null=True,
                verbose_name="Краткое описание проекта",
            ),
        ),
        migrations.AddField(
            model_name="projectsgallery",
            name="short_description_uz",
            field=models.TextField(
                help_text="Краткое описание для проекта, показывается на странице проектов",
                null=True,
                verbose_name="Краткое описание проекта",
            ),
        ),
    ]
