# Generated by Django 4.2.5 on 2023-11-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0002_remove_product_uzs_price_product_usd_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='control_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cornice_type',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='control_type',
            field=models.CharField(choices=[('manual', 'Ручной'), ('electrically_driven', 'С электроприводом')], default='manual', max_length=50, verbose_name='Тип управления'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='cornice_type',
            field=models.CharField(choices=[('aluminum', 'Алюминиевый'), ('plastic', 'Пластиковый')], default='aluminum', max_length=50, verbose_name='Тип карниза'),
        ),
    ]
