# Generated by Django 4.2.5 on 2023-10-23 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web_site", "0002_projectsgallery_description_ru_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"verbose_name": "Видео", "verbose_name_plural": "Видео"},
        ),
    ]
