# Generated by Django 4.2.5 on 2023-09-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_site", "0002_alter_product_options_category_slug_product_body_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата создания"),
        ),
    ]
