# Generated by Django 4.2.5 on 2023-09-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_site", "0003_product_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="herogallery",
            name="img",
            field=models.ImageField(
                default="", upload_to="slides/", verbose_name="Фото слайда"
            ),
        ),
    ]
