# Generated by Django 4.2.5 on 2023-11-09 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0003_alter_question_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_usd_price',
        ),
        migrations.RemoveField(
            model_name='category',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='category',
            name='length_rounding',
        ),
        migrations.RemoveField(
            model_name='category',
            name='length_rounding_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='length_rounding_uz',
        ),
        migrations.RemoveField(
            model_name='category',
            name='make_bestseller',
        ),
        migrations.RemoveField(
            model_name='category',
            name='product_length_from',
        ),
        migrations.RemoveField(
            model_name='category',
            name='product_length_to',
        ),
        migrations.RemoveField(
            model_name='category',
            name='product_width_from',
        ),
        migrations.RemoveField(
            model_name='category',
            name='product_width_to',
        ),
        migrations.RemoveField(
            model_name='category',
            name='show_on_homepage',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='category',
            name='width_rounding',
        ),
        migrations.RemoveField(
            model_name='category',
            name='width_rounding_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='width_rounding_uz',
        ),
    ]
