# Generated by Django 4.2.5 on 2023-11-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0004_alter_product_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='cornice_type',
            field=models.CharField(choices=[('aluminium', 'Алюминиевый'), ('plastic', 'Пластиковый')], default='aluminium', max_length=50, verbose_name='Тип карниза'),
        ),
    ]
