# Generated by Django 4.2.5 on 2023-09-19 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web_site", "0005_alter_subcategory_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productcoloritem",
            options={"verbose_name": "Цвет", "verbose_name_plural": "Цвета"},
        ),
        migrations.AlterModelOptions(
            name="productimageitem",
            options={
                "verbose_name": "Фото продукта",
                "verbose_name_plural": "Фотки продуктов",
            },
        ),
        migrations.AlterModelOptions(
            name="productlengthitem",
            options={
                "verbose_name": "Длина продукта",
                "verbose_name_plural": "Длина продукта",
            },
        ),
        migrations.AlterModelOptions(
            name="productoptionitem",
            options={
                "verbose_name": "Характеристика",
                "verbose_name_plural": "Характеристики",
            },
        ),
        migrations.AlterModelOptions(
            name="productwidthitem",
            options={
                "verbose_name": "Ширина продукта",
                "verbose_name_plural": "Ширина продукта",
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="web_site.category",
                verbose_name="Категория",
            ),
        ),
    ]
