# Generated by Django 4.2.5 on 2023-11-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0006_subcategory_category_common_price_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='category_common_price_uzs',
            field=models.IntegerField(default=0, help_text='Данное поле заполнять не нужно. Оно заполнится само при сохранении данного продукта', verbose_name='Цена (сум) от'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category_common_price_usd',
            field=models.SmallIntegerField(default=0, help_text='Данное поле используется чтобы отобразить среднюю стоимость продуктов данной категории на Главной странице', verbose_name='Цена (y.e) от'),
        ),
    ]
