# Generated by Django 4.2.5 on 2023-11-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0006_alter_product_category_alter_product_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Название коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Название коллекции'),
        ),
    ]
