# Generated by Django 4.2.5 on 2023-09-19 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web_site", "0006_alter_productcoloritem_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productcoloritem",
            name="product",
        ),
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="web_site.productcoloritem",
                verbose_name="Цвет продукта",
            ),
        ),
    ]
