# Generated by Django 4.2.5 on 2023-11-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0007_collection_name_ru_collection_name_uz'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='slug',
            field=models.SlugField(default='', help_text='Данное поле заполнять не нужно', verbose_name='Ссылка коллекции'),
        ),
    ]
