# Generated by Django 4.2.5 on 2023-09-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_site", "0007_remove_productcoloritem_product_product_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="placeholder",
            field=models.ImageField(
                null=True, upload_to="products/placeholders/", verbose_name="Заставка"
            ),
        ),
    ]
