# Generated by Django 4.2.5 on 2023-11-10 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0008_collection_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='web_site.collection'),
        ),
        migrations.AlterField(
            model_name='product',
            name='uzs_price',
            field=models.IntegerField(blank=True, default=0, help_text='Данное поле заполнять не нужно.', null=True, verbose_name='Цена в узбекских сумах'),
        ),
    ]
