# Generated by Django 4.2.5 on 2023-11-14 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0008_rename_category_kind_rename_category_product_kind_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subcategory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='subcategory',
            new_name='category',
        ),
    ]
