# Generated by Django 4.2.5 on 2023-11-10 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0009_product_collection_alter_product_uzs_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductManufacturerCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название страны')),
            ],
            options={
                'verbose_name': 'Страна производитель',
                'verbose_name_plural': 'Страны производители',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='web_site.productmanufacturercountry'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer_country_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='web_site.productmanufacturercountry'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer_country_uz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='web_site.productmanufacturercountry'),
        ),
    ]
