# Generated by Django 4.2.5 on 2023-11-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0010_productmanufacturercountry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmanufacturercountry',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Название страны'),
        ),
        migrations.AddField(
            model_name='productmanufacturercountry',
            name='name_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Название страны'),
        ),
    ]
