# Generated by Django 4.2.5 on 2023-11-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0010_product_uzs_price_alter_product_usd_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='usd_electrical_price',
            field=models.IntegerField(default=0, verbose_name='Цена с электроприводом в долларах'),
        ),
        migrations.AddField(
            model_name='product',
            name='uzs_electrical_price',
            field=models.IntegerField(default=0, help_text='Данное поле заполнять не нужно, цена будет рассчитываться от цены элекртопривода в долларах', verbose_name='Цена с электроприводом в суммах'),
        ),
    ]
