# Generated by Django 4.2.5 on 2023-09-19 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_site", "0011_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="make_bestseller",
            field=models.BooleanField(
                default=False,
                help_text="При выборе данного пункта, покажет все товары данной категории в секции 'Хиты продаж' ",
                verbose_name="Сделать бестселлером",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="show_on_homepage",
            field=models.BooleanField(
                default=False,
                help_text="При выборе данного пункта, все продукты этой категории будут показаны на главной странице",
                verbose_name="Показать на главной",
            ),
        ),
    ]
