# Generated by Django 4.2.5 on 2023-11-10 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0011_productmanufacturercountry_name_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='fabric_type_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fabric_type_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='manufacturer_country_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='manufacturer_country_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='property_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='property_uz',
        ),
        migrations.AddField(
            model_name='fabrictype',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Тип ткани'),
        ),
        migrations.AddField(
            model_name='fabrictype',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Тип ткани'),
        ),
        migrations.AddField(
            model_name='productproperty',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Свойство'),
        ),
        migrations.AddField(
            model_name='productproperty',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Свойство'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='web_site.productmanufacturercountry', verbose_name='Страна производитель'),
        ),
    ]
