# Generated by Django 4.2.5 on 2023-09-19 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_site", "0012_category_make_bestseller_category_show_on_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount",
            field=models.SmallIntegerField(
                default=0, null=True, verbose_name="Размер скидки"
            ),
        ),
    ]
