# Generated by Django 4.2.5 on 2023-11-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0012_remove_product_fabric_type_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='length_rounding',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Округление по длине для всех товаров категории'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='product_length_from',
            field=models.IntegerField(default=0, null=True, verbose_name='Длина от'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='product_length_to',
            field=models.IntegerField(default=0, null=True, verbose_name='Длина до'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='product_width_from',
            field=models.IntegerField(default=0, null=True, verbose_name='Ширина от'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='product_width_to',
            field=models.IntegerField(default=0, null=True, verbose_name='Ширина до'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='width_rounding',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Округление по ширине для всех товаров категории'),
        ),
    ]
