# Generated by Django 4.2.5 on 2023-11-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0013_subcategory_length_rounding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='length_rounding_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Округление по длине для всех товаров категории'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='length_rounding_uz',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Округление по длине для всех товаров категории'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='width_rounding_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Округление по ширине для всех товаров категории'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='width_rounding_uz',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Округление по ширине для всех товаров категории'),
        ),
    ]
