# Generated by Django 4.2.5 on 2024-02-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0014_alter_product_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_center_control',
            field=models.BooleanField(default=False, verbose_name='Есть ли управление по центру'),
        ),
    ]
