# Generated by Django 4.2.5 on 2023-09-22 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web_site", "0015_alter_product_subcategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "img",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="comments/",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web_site.comment",
                    ),
                ),
            ],
        ),
    ]
