# Generated by Django 4.2.5 on 2023-09-22 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web_site", "0016_commentitem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
            },
        ),
    ]
