# Generated by Django 4.2.5 on 2023-09-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0017_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='body_en',
            field=models.TextField(null=True, verbose_name='Текст отзыва'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='body_ru',
            field=models.TextField(null=True, verbose_name='Текст отзыва'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='company_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Компания автора'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='company_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Компания автора'),
        ),
        migrations.AddField(
            model_name='product',
            name='body_en',
            field=models.TextField(default='', null=True, verbose_name='Описание продукта'),
        ),
        migrations.AddField(
            model_name='product',
            name='body_ru',
            field=models.TextField(default='', null=True, verbose_name='Описание продукта'),
        ),
        migrations.AddField(
            model_name='product',
            name='fabric_type_en',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Тип ткани'),
        ),
        migrations.AddField(
            model_name='product',
            name='fabric_type_ru',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Тип ткани'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer_country_en',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Страна производитель'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer_country_ru',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Страна производитель'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(default='', max_length=255, null=True, unique=True, verbose_name='Название продукта'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(default='', max_length=255, null=True, unique=True, verbose_name='Название продукта'),
        ),
        migrations.AddField(
            model_name='product',
            name='property_en',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Свойство'),
        ),
        migrations.AddField(
            model_name='product',
            name='property_ru',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Свойство'),
        ),
        migrations.AddField(
            model_name='productcoloritem',
            name='color_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Цвет продукта'),
        ),
        migrations.AddField(
            model_name='productcoloritem',
            name='color_ru',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Цвет продукта'),
        ),
        migrations.AddField(
            model_name='productlengthitem',
            name='length_en',
            field=models.CharField(default='', max_length=100, null=True, unique=True, verbose_name='Длина'),
        ),
        migrations.AddField(
            model_name='productlengthitem',
            name='length_ru',
            field=models.CharField(default='', max_length=100, null=True, unique=True, verbose_name='Длина'),
        ),
        migrations.AddField(
            model_name='productoptionitem',
            name='descr_en',
            field=models.TextField(null=True, verbose_name='Описание характеристики'),
        ),
        migrations.AddField(
            model_name='productoptionitem',
            name='descr_ru',
            field=models.TextField(null=True, verbose_name='Описание характеристики'),
        ),
        migrations.AddField(
            model_name='productoptionitem',
            name='title_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Название характеристики'),
        ),
        migrations.AddField(
            model_name='productoptionitem',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Название характеристики'),
        ),
        migrations.AddField(
            model_name='productwidthitem',
            name='width_en',
            field=models.CharField(default='', max_length=100, null=True, unique=True, verbose_name='Ширина'),
        ),
        migrations.AddField(
            model_name='productwidthitem',
            name='width_ru',
            field=models.CharField(default='', max_length=100, null=True, unique=True, verbose_name='Ширина'),
        ),
        migrations.AddField(
            model_name='projectsgallery',
            name='subtitle_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Подзаголовок проекта'),
        ),
        migrations.AddField(
            model_name='projectsgallery',
            name='subtitle_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Подзаголовок проекта'),
        ),
        migrations.AddField(
            model_name='projectsgallery',
            name='title_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Название проекта'),
        ),
        migrations.AddField(
            model_name='projectsgallery',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Название проекта'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название подкатегории'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название подкатегории'),
        ),
    ]
