# Generated by Django 4.2.5 on 2023-09-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0018_category_name_en_category_name_ru_feedback_body_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herogallery',
            name='body_en',
            field=models.TextField(null=True, verbose_name='Описание слайдера'),
        ),
        migrations.AddField(
            model_name='herogallery',
            name='body_ru',
            field=models.TextField(null=True, verbose_name='Описание слайдера'),
        ),
        migrations.AddField(
            model_name='herogallery',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок слайдера'),
        ),
        migrations.AddField(
            model_name='herogallery',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок слайдера'),
        ),
    ]
