# Generated by Django 4.2.5 on 2023-10-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_site", "0022_feedback_author_en_feedback_author_ru"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="size_rounding",
            field=models.CharField(
                max_length=150,
                null=True,
                verbose_name="Окгруление для всех товаров категории",
            ),
        ),
    ]
