# Generated by Django 4.2.5 on 2023-10-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_site", "0023_category_size_rounding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="size_rounding",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Окгруление для всех товаров категории",
            ),
        ),
    ]
