# Generated by Django 4.2.5 on 2023-10-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_site", "0024_alter_category_size_rounding"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="size_rounding",
        ),
        migrations.AddField(
            model_name="category",
            name="length_rounding",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Округление по длине для всех товаров категории",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="width_rounding",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Округление по ширине для всех товаров категории",
            ),
        ),
    ]
