# Generated by Django 4.2.5 on 2023-10-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_site", "0026_category_length_rounding_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcategory",
            name="image",
            field=models.ImageField(
                null=True, upload_to="subcategories/", verbose_name="Фото подкатегории"
            ),
        ),
    ]
