# Generated by Django 4.2.5 on 2023-10-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_site", "0027_subcategory_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="category_usd_price",
            field=models.IntegerField(default=0, verbose_name="Стоимость в долларах"),
        ),
    ]
