# Generated by Django 4.2.5 on 2023-10-12 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0028_category_category_usd_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тип ткани')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDimming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimming', models.IntegerField(default=0, verbose_name='Затемнение')),
            ],
        ),
        migrations.CreateModel(
            name='ProductProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Свойство')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='dimming',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='web_site.productdimming', verbose_name='Затемнение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fabric_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='web_site.fabrictype', verbose_name='Тип ткани'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fabric_type_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='web_site.fabrictype', verbose_name='Тип ткани'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fabric_type_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='web_site.fabrictype', verbose_name='Тип ткани'),
        ),
        migrations.AlterField(
            model_name='product',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='web_site.productproperty', verbose_name='Свойство'),
        ),
        migrations.AlterField(
            model_name='product',
            name='property_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='web_site.productproperty', verbose_name='Свойство'),
        ),
        migrations.AlterField(
            model_name='product',
            name='property_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='web_site.productproperty', verbose_name='Свойство'),
        ),
    ]
