# Generated by Django 4.2.5 on 2023-10-12 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0029_fabrictype_productdimming_productproperty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productwidthitem',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='fabrictype',
            options={'verbose_name': 'Тип ткани', 'verbose_name_plural': 'Типы ткани'},
        ),
        migrations.AlterModelOptions(
            name='productdimming',
            options={'verbose_name': 'Затеменение', 'verbose_name_plural': 'Затемнения'},
        ),
        migrations.AlterModelOptions(
            name='productproperty',
            options={'verbose_name': 'Свойство', 'verbose_name_plural': 'Свойства'},
        ),
        migrations.DeleteModel(
            name='ProductLengthItem',
        ),
        migrations.DeleteModel(
            name='ProductWidthItem',
        ),
    ]
