# Generated by Django 4.2.5 on 2023-10-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0030_remove_productwidthitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='product_length_from',
            field=models.IntegerField(default=0, verbose_name='Длина от'),
        ),
        migrations.AddField(
            model_name='category',
            name='product_length_to',
            field=models.IntegerField(default=0, verbose_name='Длина до'),
        ),
        migrations.AddField(
            model_name='category',
            name='product_width_from',
            field=models.IntegerField(default=0, verbose_name='Ширина от'),
        ),
        migrations.AddField(
            model_name='category',
            name='product_width_to',
            field=models.IntegerField(default=0, verbose_name='Ширина до'),
        ),
    ]
