# Generated by Django 4.2.5 on 2023-10-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0031_category_product_length_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='product_length_from',
            field=models.IntegerField(default=0, null=True, verbose_name='Длина от'),
        ),
        migrations.AlterField(
            model_name='category',
            name='product_length_to',
            field=models.IntegerField(default=0, null=True, verbose_name='Длина до'),
        ),
        migrations.AlterField(
            model_name='category',
            name='product_width_from',
            field=models.IntegerField(default=0, null=True, verbose_name='Ширина от'),
        ),
        migrations.AlterField(
            model_name='category',
            name='product_width_to',
            field=models.IntegerField(default=0, null=True, verbose_name='Ширина до'),
        ),
    ]
