# Generated by Django 4.2.5 on 2023-10-13 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web_site", "0032_alter_category_product_length_from_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="usd_price",
        ),
    ]
