# Generated by Django 4.2.5 on 2023-10-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0034_alter_product_uzs_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesOnAboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pages/about/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': "Фотка на странице 'О компании'",
                'verbose_name_plural': "Фотки на странице 'О компании'",
            },
        ),
    ]
