# Generated by Django 4.2.5 on 2023-10-17 13:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_site", "0036_subcategory_discount_alter_product_uzs_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectsgallery",
            name="description",
            field=ckeditor.fields.RichTextField(
                null=True, verbose_name="Описание проекта"
            ),
        ),
        migrations.AddField(
            model_name="projectsgallery",
            name="slug",
            field=models.SlugField(null=True, verbose_name="Слаг"),
        ),
    ]
