# Generated by Django 4.2.5 on 2023-10-17 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web_site", "0037_projectsgallery_description_projectsgallery_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectsgallery",
            name="short_description",
            field=models.TextField(
                help_text="Краткое описание для проекта, показывается на странице проектов",
                null=True,
                verbose_name="Краткое описание проекта",
            ),
        ),
        migrations.AlterField(
            model_name="projectsgallery",
            name="subtitle",
            field=models.CharField(
                help_text="Показывается на главной странице",
                max_length=255,
                verbose_name="Подзаголовок проекта",
            ),
        ),
        migrations.AlterField(
            model_name="projectsgallery",
            name="subtitle_en",
            field=models.CharField(
                help_text="Показывается на главной странице",
                max_length=255,
                null=True,
                verbose_name="Подзаголовок проекта",
            ),
        ),
        migrations.AlterField(
            model_name="projectsgallery",
            name="subtitle_ru",
            field=models.CharField(
                help_text="Показывается на главной странице",
                max_length=255,
                null=True,
                verbose_name="Подзаголовок проекта",
            ),
        ),
        migrations.CreateModel(
            name="ProjectsGalleryImageItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to="projects_gallery/addons/",
                        verbose_name="Дополнительное фото",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="web_site.projectsgallery",
                        verbose_name="Проект",
                    ),
                ),
            ],
        ),
    ]
