# Generated by Django 4.2.5 on 2023-10-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_site", "0038_projectsgallery_short_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectsgalleryimageitem",
            options={
                "verbose_name": "Дополнительное фото",
                "verbose_name_plural": "Дополнительные фото",
            },
        ),
        migrations.RemoveField(
            model_name="subcategory",
            name="discount",
        ),
        migrations.AddField(
            model_name="category",
            name="discount",
            field=models.SmallIntegerField(default=0, verbose_name="Процент скидки"),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="has_discount",
            field=models.BooleanField(
                default=False,
                help_text="Есть ли скидка для всех товаров этой подкатегории",
                verbose_name="Размер скидки",
            ),
        ),
    ]
