# Generated by Django 4.2.5 on 2023-10-23 20:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=500, unique=True, verbose_name="Заголовок статьи"
                    ),
                ),
                ("photo", models.ImageField(upload_to="blog/", verbose_name="Фото")),
                (
                    "short_description",
                    models.CharField(max_length=500, verbose_name="Краткое описание"),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        verbose_name="Полное описание статьи"
                    ),
                ),
                ("slug", models.SlugField(null=True, verbose_name="Слаг")),
            ],
            options={
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
    ]
