# Generated by Django 4.2.5 on 2023-10-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="slug",
            field=models.SlugField(null=True, verbose_name="Слаг"),
        ),
    ]
