# Generated by Django 4.2.5 on 2023-10-23 20:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="description_ru",
            field=ckeditor.fields.RichTextField(
                null=True, verbose_name="Полное описание статьи"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="description_uz",
            field=ckeditor.fields.RichTextField(
                null=True, verbose_name="Полное описание статьи"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="name_ru",
            field=models.CharField(
                max_length=500, null=True, unique=True, verbose_name="Заголовок статьи"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="name_uz",
            field=models.CharField(
                max_length=500, null=True, unique=True, verbose_name="Заголовок статьи"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="short_description_ru",
            field=models.CharField(
                max_length=500, null=True, verbose_name="Краткое описание"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="short_description_uz",
            field=models.CharField(
                max_length=500, null=True, verbose_name="Краткое описание"
            ),
        ),
    ]
