# Generated by Django 4.2.5 on 2023-12-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='product_selected_height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='product_selected_width',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
