# Generated by Django 4.2.5 on 2023-12-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_orderproduct_product_selected_control_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'Продукт в корзине', 'verbose_name_plural': 'Продукты в корзине'},
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product_selected_control',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product_selected_control_type',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product_selected_cornice_type',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product_selected_height',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product_selected_width',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
